services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - directus

  directus:
    image: directus/directus:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SECRET: "latronspem-fiestalok"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      ADMIN_EMAIL: "contact@fiestalok.fr"
      ADMIN_PASSWORD: "fiestalok2sxb!"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://fiestalok.fr,http://localhost:5174"
      PUBLIC_URL: "https://back.fiestalok.fr"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./database:/directus/database

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
